version: '2'
services:
  ckapache:
    image: hyperprog/codkepdebian
    links:
      - ckdatabase
    ports:
      - "80:80"
    volumes:
      - ./site:/var/www/html/site
      - ./data:/var/www/html/data
  ckdatabase:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: codkep_database
    volumes:
      - ./dbfiles/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: codkepapptest
      MYSQL_DATABASE: codkep
